import { BaseEntity } from './base.entity';

/**
 * Entidade de domínio: Item (Produto) - DDD.
 * Representa um item/produto do catálogo do PDV.
 * Estoque: inicia em 0; entrada via entrada de notas/pedidos (addQuantity); saída no fechamento da venda (deductQuantity).
 * Margem de lucro % = ((preço venda - preço custo) / preço custo) × 100 (markup).
 */
export class Item extends BaseEntity<string> {
  constructor(
    id: string,
    private _name: string,
    private _price: number,
    private _costPrice: number,
    private _sku: string,
    /** Supplier/internal code manually provided on product creation. */
    private _supplierCode: string,
    /** Scannable barcode generated by the system (GTIN-13). */
    private _barcode: string,
    private _quantity: number,
    private _description: string = '',
    private _createdAt: Date = new Date(),
    private _updatedAt: Date = new Date(),
  ) {
    super(id);
  }

  get name(): string {
    return this._name;
  }

  get price(): number {
    return this._price;
  }

  /** Preço de custo do item. */
  get costPrice(): number {
    return this._costPrice;
  }

  /** Margem de lucro em percentual (markup): ((preço venda - preço custo) / preço custo) × 100. Se custo for 0, retorna 0. */
  get marginPercent(): number {
    if (this._costPrice <= 0) return 0;
    return Number(
      (((this._price - this._costPrice) / this._costPrice) * 100).toFixed(2),
    );
  }

  get sku(): string {
    return this._sku;
  }

  /** Supplier/internal code (manually provided). */
  get supplierCode(): string {
    return this._supplierCode;
  }

  /** Scannable barcode (GTIN-13) generated by the system. */
  get barcode(): string {
    return this._barcode;
  }

  get quantity(): number {
    return this._quantity;
  }

  get description(): string {
    return this._description;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  updateName(name: string): void {
    if (!name?.trim()) {
      throw new Error('Name cannot be empty');
    }
    this._name = name.trim();
    this._updatedAt = new Date();
  }

  updatePrice(price: number): void {
    if (price < 0) {
      throw new Error('Price cannot be negative');
    }
    this._price = price;
    this._updatedAt = new Date();
  }

  updateCostPrice(costPrice: number): void {
    if (costPrice < 0) {
      throw new Error('Cost price cannot be negative');
    }
    this._costPrice = costPrice;
    this._updatedAt = new Date();
  }

  updateSku(sku: string): void {
    if (!sku?.trim()) {
      throw new Error('SKU cannot be empty');
    }
    this._sku = sku.trim();
    this._updatedAt = new Date();
  }

  updateSupplierCode(supplierCode: string): void {
    if (!supplierCode?.trim()) {
      throw new Error('Supplier code cannot be empty');
    }
    this._supplierCode = supplierCode.trim();
    this._updatedAt = new Date();
  }

  updateDescription(description: string): void {
    this._description = description ?? '';
    this._updatedAt = new Date();
  }

  /** Altera a quantidade em estoque (uso interno; preferir addQuantity/deductQuantity). */
  updateQuantity(quantity: number): void {
    if (quantity < 0 || !Number.isInteger(quantity)) {
      throw new Error('Quantity must be a non-negative integer');
    }
    this._quantity = quantity;
    this._updatedAt = new Date();
  }

  /** Entrada de estoque (entrada de notas/pedidos). Quantidade deve ser inteira positiva. */
  addQuantity(amount: number): void {
    if (amount <= 0 || !Number.isInteger(amount)) {
      throw new Error('Amount must be a positive integer');
    }
    this._quantity += amount;
    this._updatedAt = new Date();
  }

  /** Saída de estoque (ex.: fechamento de venda). Valida estoque suficiente. */
  deductQuantity(amount: number): void {
    if (amount <= 0 || !Number.isInteger(amount)) {
      throw new Error('Amount must be a positive integer');
    }
    if (this._quantity < amount) {
      throw new Error(
        `Insufficient stock: available ${this._quantity}, requested ${amount}`,
      );
    }
    this._quantity -= amount;
    this._updatedAt = new Date();
  }
}
